### ISSUE TITLE
missing simulations for ABR?

### ISSUE THREAD

**Issue by emvolz** [cathyqqtao/RTDT#1]
I see that there are only 38 simulations for ABR but the manuscript says there are 50? Are some missing?

**Comment by cathyqqtao** [comment]
Hi,

We removed datasets with identical sequences, as we have mentioned in the manuscript. After the removal of those datasets, it left 38 datasets for ABR in the Flu simulation.

**Comment by emvolz** [comment]
Ok - understood. 

Can you re-run your experiment with the latest version of treedater (0.5.0) now on cran? Performance with this version seems to be much better, and I think the main reason you found poor results with ABR was poor optimization- it did not by default start optimization from a diverse range of starting rates. You also could have fixed this by using the 'numStartConditions' which was in the documentation. I have changed this default setting.

**Comment by cathyqqtao** [comment]
Dear Dr. Volz,

Yes, treedater (v0.5.0) now performed much better than the previous version (v0.3.0, which we used in the study) for the autocorrelated datasets under the default setting. Thank you for improving the software.

Best,
Qiqing

**Comment by emvolz** [comment]
No - thank you for pointing out the issue. In the future however, it would be good to study the docs and get in touch with developers when you discover major issues.
